#! /bin/env bash
#export https_proxy=""
newrelic_api_key=""
newrelic_account_id=""
host_name="$(hostname)"
time_stamp="$(date "+%s")"
chunk_size=900
data_center="DDC"
environment="DEV"
team="vAuto DBA"

process_mapfile() {
  start_loop=$1
  end_loop=$2
  while [ ${start_loop} -le ${end_loop} ] ; do
    echo "   ${MAPFILE[${start_loop}]}"
    ((start_loop++))
  done
}

ps axo uname:15,euser:15,group,egroup,pid,ppid,nlwp,pcpu,pgrp,cmd

#mapfile -O 1 -s 2 -t < <(ps -eLF | \
mapfile -O 1 -t < <(ps haxo uname:15,euser:15,group:15,egroup:15,pid,ppid,nlwp,pgrp,comm,cmd | \
                    awk '{print $1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10}')
entry=1
while [ $entry -le ${#MAPFILE[@]} ] ; do
  end_loop=$((entry + chunk_size))
  ((end_loop--))

  if [ ${end_loop} -gt ${#MAPFILE[@]} ] ; then
    end_loop=${#MAPFILE[@]}
  fi

#  echo "Start loop: ${entry}  End loop: ${end_loop}"
  file_name="export_osProcessThreadCount_${end_loop}_${PPID}.json"
  file_name="export_osProcessThreadCount_${end_loop}.json"
  process_mapfile ${entry} ${end_loop} | \
    awk -v host_name="${host_name}" \
        -v time_stamp="${time_stamp}" \
        -v data_center="${data_center}" \
        -v environment="${environment}" \
        -v team="${team}" \
        ' BEGIN { print "[" ; }
          { print  " {" ;
            print  "   \"eventType\":\"osProcessThreadCount\"," ;
            print  "   \"timestamp\":"time_stamp"," ;
            print  "   \"hostname\":\""host_name"\"," ;
            print  "   \"data_center\":\""data_center"\"," ;
            print  "   \"environment\":\""environment"\"," ;
            print  "   \"team\":\""team"\"," ;
            print  "   \"userName\":\""$1"\"," ;
            print  "   \"effectiveUser\":\""$2"\"," ;
            print  "   \"groupName\":\""$3"\"," ;
            print  "   \"effectiveGroup\":\""$4"\"," ;
            print  "   \"processId\":"$5"," ;
            print  "   \"parentProcessId\":"$6"," ;
            print  "   \"threadCount\":"$7"," ;
            print  "   \"processGroup\":"$8"," ;
            print  "   \"command\":\""$9"\"," ;
            print  "   \"commandLine\":\""$10"\"" ;
            print  " }," ;
          }' > "${file_name}"
  echo "   ${MAPFILE[${end_loop}]}" | \
    awk -v host_name="${host_name}" \
        -v time_stamp="${time_stamp}" \
        -v data_center="${data_center}" \
        -v environment="${environment}" \
        -v team="${team}" \
        ' { print  " {" ;
            print  "   \"eventType\":\"osProcessThreadCount\"," ;
            print  "   \"timestamp\":"time_stamp"," ;
            print  "   \"hostname\":\""host_name"\"," ;
            print  "   \"data_center\":\""data_center"\"," ;
            print  "   \"environment\":\""environment"\"," ;
            print  "   \"team\":\""team"\"," ;
            print  "   \"userName\":\""$1"\"," ;
            print  "   \"effectiveUser\":\""$2"\"," ;
            print  "   \"groupName\":\""$3"\"," ;
            print  "   \"effectiveGroup\":\""$4"\"," ;
            print  "   \"processId\":"$5"," ;
            print  "   \"parentProcessId\":"$6"," ;
            print  "   \"threadCount\":"$7"," ;
            print  "   \"processGroup\":"$8"," ;
            print  "   \"command\":\""$9"\"," ;
            print  "   \"commandLine\":\""$10"\"" ;
            print  " }" ;
          }
      END { print "]" } ' >> "${file_name}"
#    gzip -c "${file_name}" | \
#    curl -X POST \
#         -H "Content-Type: application/json" \
#         -H "Content-Encoding: gzip" \
#         -H "X-Insert-Key: ${newrelic_api_key}" \
#         https://insights-collector.newrelic.com/v1/accounts/${newrelic_account_id}/events --data-binary @-
  echo
  entry=$((end_loop + 1))
done
